POST http://localhost:3000/sync/responsaveis/cancelamentos

###

POST http://localhost:3000/sync/responsaveis/cancelamentos/responsavel
Content-Type: application/json

{
  "CD_Periodo_Letivo": "2026",
  "CD_Pessoa": 123456,
  "TP_Origem_Disparo": "REPROCESSAMENTO"
}

###

POST http://localhost:3000/sync/responsaveis/cancelamentos/responsavel
Content-Type: application/json

{
  "CD_Periodo_Letivo": "2026",
  "CD_CPF": "10240205766",
  "TP_Origem_Disparo": "REPROCESSAMENTO"
}

###

POST http://localhost:3000/sync/responsaveis/cancelamentos/responsavel
Content-Type: application/json

{
  "CD_Periodo_Letivo": "2026",
  "CD_Pessoa": 123456,
  "CD_CPF": "12345678901",
  "TP_Origem_Disparo": "WEBHOOK"
}
