POST http://localhost:3000/sync/alunos

###

POST http://localhost:3000/sync/alunos/cancelamentos

###

POST http://localhost:3000/webhooks/alunos
Content-Type: application/json

{
  "CD_Registro_Academico": "123456",
  "CD_Coligada": 1
}
