### Buscar usuário TOTVS pelo código (RA do aluno)
### Substitua o código no final da URL pelo RA desejado
GET http://201.148.210.189:8052/rmsrestdataserver/rest/GlbUsuarioData/75311568062
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODSISTEMA: S
Content-Type: application/json

###
PUT http://201.148.210.189:8052/rmsrestdataserver/rest/GlbUsuarioData/75311568062
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODSISTEMA: S
CODCOLIGADA: 1
Content-Type: application/json


{
 
 "id": "75311568062",
    "CODUSUARIO": "75311568062",
    "NOME": "RYAN CEL TESTE",
    "STATUS": 1,
    "DATAINICIO": "2026-03-20T00:00:00-03:00",
    "DATAEXPIRACAO": null,
    "CONFIRMABTNOK": 1,
    "SENHA": "#P=False#PT=None#WF=10#HT=SHA256#HA=Bcrypt#V=4.0.2.0#H=$2a$10$SmVqTwkArfIgRSzvIdO4Wu/4kv8up1AYaCJ.8L40RTpbDUk59JEE6",
    "CONTROLE": -24445,
    "ULTIMACOLIGADA": null,
    "CODACESSO": "Acesso03",
    "DTAEXPSENHA": null,
    "DIASEXPSENHA": null,
    "OBRIGAALTERARSENHA": "F",
    "NUMLOGININVALIDO": null,
    "DATALOGININVALIDO": null,
    "EMAIL": "2026100999@aluno.cel.g12.br",
    "ACESSONET": "T",
    "DATAULTIMOACESSO": null,
    "CODUSUARIOREDE": null,
    "DOMINIOREDE": null,
    "LIVEID": null,
    "USUARIOTWITTER": null,
    "SENHATWITTER": null,
    "USUARIOFACEBOOK": null,
    "SENHAFACEBOOK": null,
    "USUARIOLINKEDIN": null,
    "SENHALINKEDIN": null,
    "FULLDETERMINED": "",
    "USERID": "6f6bc038-d845-494b-9213-4f0c3690428b",
    "INTEGRADOFLUIG": null,
    "USERIDFLUIGIDENTITY": null,
    "IGNORARAUTENTICACAOLDAP": "F",
    "NOMESOCIAL": null,
    "DATAULTIMOACESSOVALIDO": null,
    "CODEXTERNO": null,
    "ULTIMASSENHAS": null,
    "INTERNO1": null,
    "RECCREATEDON": "2026-03-20T15:29:14-03:00",
    "RECMODIFIEDON": "2026-03-30T14:45:20-03:00",
    "RECCREATEDBY": "PortalMatriculaInt",
    "RECMODIFIEDBY": "PortalMatriculaInt",
    "GPERMIS": [
 {
        "id": "1$_$S$_$75311568062",
        "parent_id": "75311568062",
        "CODCOLIGADA": 1,
        "CODSISTEMA": "S",
        "CODUSUARIO": "75311568062",
        "SUPERVISOR": 0,
        "CONTROLE": 25752,
        "CRIARELAT": 0,
        "RECCREATEDBY": "PortalMatriculaInt",
        "RECCREATEDON": "2026-03-20T15:29:17-03:00",
        "RECMODIFIEDBY": "PortalMatriculaInt",
        "RECMODIFIEDON": "2026-03-30T15:09:54-03:00",
        "GUSRPERFIL": [
          {
            "id": "1$_$75311568062$_$S$_$Aluno CEL",
            "parent_id": "1$_$S$_$75311568062",
            "CODCOLIGADA": 1,
            "CODUSUARIO": "75311568062",
            "CODSISTEMA": "S",
            "CODPERFIL": "Aluno CEL",
            "INDICE": 0,
            "CONTROLE": 7228,
            "RECCREATEDBY": "PortalMatriculaInt",
            "RECCREATEDON": "2026-03-30T15:08:43-03:00",
            "RECMODIFIEDBY": "PortalMatriculaInt",
            "RECMODIFIEDON": "2026-03-30T15:09:54-03:00",
            "STATUS": 1,
            "IDPERFIL": "Aluno CEL_S"
          },
          {
            "id": "1$_$75311568062$_$S$_$Aluno CEL 2",
            "parent_id": "1$_$S$_$75311568062",
            "CODCOLIGADA": 1,
            "CODUSUARIO": "75311568062",
            "CODSISTEMA": "S",
            "CODPERFIL": "Aluno CEL 2",
            "INDICE": 0,
            "CONTROLE": -14662,
            "RECCREATEDBY": "19799694779",
            "RECCREATEDON": "2026-03-30T14:45:15-03:00",
            "RECMODIFIEDBY": "PortalMatriculaInt",
            "RECMODIFIEDON": "2026-03-30T15:09:54-03:00",
            "STATUS": 1,
            "IDPERFIL": "Aluno CEL 2"
          },
          {
            "id": "1$_$75311568062$_$S$_$Coordenação",
            "parent_id": "1$_$S$_$75311568062",
            "CODCOLIGADA": 1,
            "CODUSUARIO": "75311568062",
            "CODSISTEMA": "S",
            "CODPERFIL": "Coordenação",
            "INDICE": 0,
            "CONTROLE": -23095,
            "RECCREATEDBY": "19799694779",
            "RECCREATEDON": "2026-03-20T15:32:16-03:00",
            "RECMODIFIEDBY": "PortalMatriculaInt",
            "RECMODIFIEDON": "2026-03-30T15:09:54-03:00",
            "STATUS": 1,
            "IDPERFIL": "Coordenação CEL"
          }
        ]
      }
    ]

}


###

GET http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==

###

### Diagnóstico UsuarioFilial - GET antes/depois
### Ajuste PK: CODCOLIGADA$_$CODTIPOCURSO$_$CODFILIAL$_$CODUSUARIO
GET http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 7
CODTIPOCURSO: 1
CODSISTEMA: S

###

### Diagnóstico UsuarioFilial - DELETE revogação correta
DELETE http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 7
CODTIPOCURSO: 1
CODSISTEMA: S

###

POST http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 2
CODSISTEMA: "S"
Content-Type: application/json

{
  "SUsuarioFilial": {
    "CODCOLIGADA": 1,
    "CODTIPOCURSO": 1,
    "CODFILIAL": 2,
    "CODUSUARIO": "75311568062",
    "ACESSO": "1"
  }
}
