### Buscar usuário TOTVS pelo código (RA do aluno)
### Substitua o código no final da URL pelo RA desejado
GET http://201.148.210.189:8052/rmsrestdataserver/rest/GlbUsuarioData/10240205766
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODSISTEMA: S
Content-Type: application/json

###
PATCH http://201.148.210.189:8052/rmsrestdataserver/rest/GlbUsuarioData/10240205766
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODSISTEMA: S
CODCOLIGADA: 1
Content-Type: application/json


{
   "input": [{ "id": "10240205766",
    "CODUSUARIO": "10240205766",
    "NOME": "ANDERSON FLAVIO DIAS AGUIAR",
    "STATUS": 0,
    "DATAINICIO": "2020-01-01T00:00:00-03:00",
    "DATAEXPIRACAO": null,
    "CONFIRMABTNOK": 1,
    "SENHA": "#P=False#PT=None#WF=10#HT=SHA256#HA=Bcrypt#V=4.0.2.0#H=$2a$10$4uDx.zgPhcrtolSqIxZWweWvG0OBtkxNskeqf/uWT9VRfh66d1lWW",
    "CONTROLE": 11349,
    "ULTIMACOLIGADA": null,
    "CODACESSO": "Acesso03",
    "DTAEXPSENHA": null,
    "DIASEXPSENHA": null,
    "OBRIGAALTERARSENHA": "F",
    "NUMLOGININVALIDO": null,
    "DATALOGININVALIDO": null,
    "GPERMIS": [
      {
        "id": "1$_$S$_$10240205766",
        "parent_id": "10240205766",
        "CODCOLIGADA": 1,
        "CODSISTEMA": "S",
        "CODUSUARIO": "10240205766",
        "SUPERVISOR": 0,
        "CONTROLE": 10326,
        "CRIARELAT": 0,
        "RECCREATEDBY": "PortalMatriculaInt",
        "RECCREATEDON": "2024-06-26T16:35:55-03:00",
        "RECMODIFIEDBY": "PortalMatriculaInt",
        "RECMODIFIEDON": "2026-05-06T14:05:45-03:00",
        "GUSRPERFIL": [
          {
            "id": "1$_$10240205766$_$S$_$RespAcad_CEL",
            "parent_id": "1$_$S$_$10240205766",
            "CODCOLIGADA": 1,
            "CODUSUARIO": "10240205766",
            "CODSISTEMA": "S",
            "CODPERFIL": "RespAcad_CEL",
            "INDICE": 0,
            "CONTROLE": -28979,
            "RECCREATEDBY": "pedro",
            "RECCREATEDON": "2024-07-01T12:30:15-03:00",
            "RECMODIFIEDBY": "PortalMatriculaInt",
            "RECMODIFIEDON": "2026-05-06T14:05:45-03:00",
            "STATUS": 1,
            "IDPERFIL": "RespAcad_CEL"
          },
          {
            "id": "1$_$10240205766$_$S$_$RespFinanc_CEL",
            "parent_id": "1$_$S$_$10240205766",
            "CODCOLIGADA": 1,
            "CODUSUARIO": "10240205766",
            "CODSISTEMA": "S",
            "CODPERFIL": "RespFinanc_CEL",
            "INDICE": 0,
            "CONTROLE": 32110,
            "RECCREATEDBY": "PortalMatriculaInt",
            "RECCREATEDON": "2024-06-26T16:35:55-03:00",
            "RECMODIFIEDBY": "PortalMatriculaInt",
            "RECMODIFIEDON": "2026-05-08T08:04:05-03:00",
            "STATUS": 0,
            "IDPERFIL": "RespFinanc_CEL"
          }
        ]
      }
    ]
  }]
}



###

GET http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==

###

### Diagnóstico UsuarioFilial - GET antes/depois
### Ajuste PK: CODCOLIGADA$_$CODTIPOCURSO$_$CODFILIAL$_$CODUSUARIO
GET http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 7
CODTIPOCURSO: 1
CODSISTEMA: S

###

### Diagnóstico UsuarioFilial - DELETE revogação correta
DELETE http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData/1$_$1$_$7$_$2019100186
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 7
CODTIPOCURSO: 1
CODSISTEMA: S

###

POST http://201.148.210.189:8052/rmsrestdataserver/rest/EduUsuarioFilialData
Authorization: Basic UG9ydGFsTWF0cmljdWxhSW50Oms4Szl5cnBINFpRVXZzVg==
CODCOLIGADA: 1
CODFILIAL: 2
CODSISTEMA: "S"
Content-Type: application/json

{
  "SUsuarioFilial": {
    "CODCOLIGADA": 1,
    "CODTIPOCURSO": 1,
    "CODFILIAL": 2,
    "CODUSUARIO": "75311568062",
    "ACESSO": "1"
  }
}
